title: Kelsey's Playground
logo: /assets/img/logo.jpg
description: image from https://quasi01.wixsite.com/teapot
description: to be continued
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
